name: Docker Image CI

on:
  push:
    branches: [ "master" , "dockertest"]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dvet:$(date +%s) --tag dvet:latest
